version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: bgm_backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./model_training:/app/model_training
      - ./backend:/app
    networks:
      - bgm_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: bgm_frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - bgm_network

networks:
  bgm_network:
    driver: bridge
